### ISSUE TITLE
DAST test - wrong results path

### ISSUE THREAD

**Issue by Koncpa** [RedHat-SP-Security/tang-operator-tests#96]
After recent changes in [rapidast](https://github.com/RedHatProductSecurity/rapidast/commit/6018bcb062e245cf5fe7507f0732248683d63af8) the DAST test start failing due change of path for rapidast results. Need to adjust it in our test.. 

`:: [ 15:08:06 ] :: [  BEGIN   ] :: Extracting DAST results :: actually running 'bash ./helm/results.sh 2>/dev/null'
pod/rapiterm-1463 created
pod/rapiterm-1463 condition met
pod "rapiterm-1463" deleted
:: [ 15:08:43 ] :: [   PASS   ] :: Extracting DAST results (Expected 0, got 0)
ls: cannot access '/tmp/tmp.UawrYmVXgC/rapidast/tangservers/DAST*tangservers/': No such file or directory
:: [ 15:08:43 ] :: [   FAIL   ] :: Checking report_dir not empty (Assert: "" should not equal "")`

**Comment by sarroutbi** [comment]
This issue is related to rapidast version being used. I will upload a PR to fix this
